name: 'Build an RPM from an Elements project'
description: 'Build an RPM from an Elements project'
inputs:
  build-dir:
    description: 'Build directory'
    required: false
    default: build
  release:
    description: 'Release number'
    required: false
    default:
outputs:
  rpm-dir:
    description: 'Directory where rpms are'
    value: ${{ inputs.build-dir }}/Packages/RPM/RPMS/x86_64/
  srpm-dir:
    description: 'Directory where source rpms are'
    value: ${{ inputs.build-dir }}/Packages/RPM/SRPMS/
runs:
  using: composite
  steps:
    - shell: bash
      run:  ${GITHUB_ACTION_PATH}/build-rpm.sh "${{ inputs.build-dir }}" "${{ inputs.release }}"
