name: 'Upload RPMs to the repository'
description: 'Upload RPMs to the repository'
inputs:
  rpm-dir:
    description: 'Location of the RPMs'
    required: true
  srpm-dir:
    description: 'Location of the source RPMs'
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run:  ${GITHUB_ACTION_PATH}/upload-rpm.sh "${{ inputs.rpm-dir }}" "${{ inputs.srpm-dir }}"
