name: 'Upload RPMs to Artifactory'
description: 'Upload RPMs to Artifactory'
inputs:
  path:
    description: 'Location of the RPMs'
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run:  /__w/_actions/astrorama/actions/master/upload-rpm/upload-rpm.sh "${{ inputs.path }}"
