name: Astrorama Build
description: Astrorama Build Steps
inputs:
  os-type:
    description: Operative System
    required: true
  os-version:
    description: Operative System Version
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get package name and version
      id: package-version
      uses: astrorama/actions/elements-project@master
    - name: Install dependencies
      uses: astrorama/actions/setup-dependencies@master
      with:
        dependency-list: .github/workflows/dependencies.txt
    - name: Build
      id: build
      uses: astrorama/actions/elements-build-rpm@master
    - name: Upload RPM to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.os-type }}${{ inputs.os-version }}
        path: ${{ steps.build.outputs.rpm-dir }}/*.rpm
        retention-days: 15
    - name: Setup jfrog cli
      if: ${{ github.event_name != 'pull_request' }}
      uses: jfrog/setup-jfrog-cli@v1
      env:
        JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
    - name: Upload RPM to Artifactory
      if: ${{ github.event_name != 'pull_request' }}
      uses: astrorama/actions/upload-rpm@master
      with:
        os_type: ${{ inputs.os-type }}
        os_version: ${{ inputs.os-version }}
        os_arch: x86_64
        path: ${{ steps.build.outputs.rpm-dir }}

