name: 'Elements Project'
description: 'Get name and version of an Elements project'
outputs:
  project:
    description: 'Project name'
    value: ${{ steps.elements-project-version.outputs.project }}
  version:
    description: 'Project version'
    value: ${{ steps.elements-project-version.outputs.version }}
runs:
  using: 'composite'
  steps:
    - id: elements-project-version
      shell: bash
      run: |
        echo "{project}={$(grep '^elements_project' CMakeLists.txt | sed 's/.*(//'| cut -d' ' -f1)}" >> $GITHUB_OUTPUT
        echo "{version}={$(grep '^elements_project' CMakeLists.txt | sed 's/.*(//' | sed 's/[^ ]* //' | sed 's/ .*//')}" >> $GITHUB_OUTPUT
