name: 'Setup dependencies'
description: 'Configure repositories and install dependencies'
inputs:
  dependency-list:
    description: 'File with the list of dependencies'
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run:  ${GITHUB_ACTION_PATH}/setup-repositories.sh
    - shell: bash
      run: ${GITHUB_ACTION_PATH}/install-dependencies.sh "${{ inputs.dependency-list }}"
