name: 'Setup dependencies'
description: 'Configure repositories and install dependencies'
inputs:
  dependency-list:
    description: 'File with the list of dependencies'
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run:  /__w/_actions/astrorama/actions/master/setup-dependencies/setup-repositories.sh
    - shell: bash
      run: /__w/_actions/astrorama/actions/master/setup-dependencies/install-dependencies.sh "${{ inputs.dependency-list }}"
